version: '3.3'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"

services:
  flask-server:
    image: python:3.11.6
    working_dir: /usr/app/
    volumes:
      - ./flask-server/:/usr/app/
    ports:
      - "5000:5000"
    command: bash -c "pip install -r ./requirements.txt && python3 ./server.py"
    networks:
      my_network:
        ipv4_address: "172.20.0.2"

  react-frontend:
    image: node:14
    ports:
      - "80:3000"
    depends_on:
      - flask-server
    working_dir: /usr/app
    volumes:
      - ./react-frontend/:/usr/app/
    command: bash -c "npm install && npm start"
    networks:
      my_network:
        ipv4_address: "172.20.0.3"