version: '3.3'

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"

services:
  flask-server:
    build:
      context: ../flask-server
    networks:
      my_network:
        ipv4_address: "172.20.0.2"
    ports:
      - "5000:5000"

  react-frontend:
    image: node:14
    ports:
      - "80:3000"
    depends_on:
      - flask-server
    working_dir: /usr/app
    volumes:
      - react-data:/usr/app
    privileged: true
    command: bash -c "npm install && npm start"

volumes:
  react-data:
    driver: local
    driver_opts:
        type: none
        device: ../react-frontend
        o: bind